### ISSUE TITLE
Got error on first run

### ISSUE THREAD

**Issue by WillyRL** [ainoya/stf-bot#1]
Hi There,

Really appreciate for your works with this slack bot, but i found problem when running it

```
ubuntu@ip:~/stf-bot$ node main.js
url.js:555
    throw new TypeError('Parameter "urlObj" must be an object, not ' +
    ^

TypeError: Parameter "urlObj" must be an object, not undefined
    at urlFormat (url.js:555:11)
    at new Request (/home/ubuntu/stf-bot/node_modules/superagent/lib/node/index.js:128:37)
    at request (/home/ubuntu/stf-bot/node_modules/superagent/lib/request.js:29:10)
    at Function.request.(anonymous function) [as get] (/home/ubuntu/stf-bot/node_modules/superagent/lib/node/index.js:1030:15)
    at SuperagentHttpClient.execute (/home/ubuntu/stf-bot/node_modules/swagger-client/lib/http.js:204:26)
    at module.exports.SwaggerHttp.execute (/home/ubuntu/stf-bot/node_modules/swagger-client/lib/http.js:83:10)
    at module.exports.SwaggerClient.build (/home/ubuntu/stf-bot/node_modules/swagger-client/lib/client.js:226:23)
    at module.exports.SwaggerClient.initialize (/home/ubuntu/stf-bot/node_modules/swagger-client/lib/client.js:151:17)
    at new module.exports (/home/ubuntu/stf-bot/node_modules/swagger-client/lib/client.js:104:17)
    at Object.<anonymous> (/home/ubuntu/stf-bot/main.js:19:14)
```

**Comment by WillyRL** [comment]
Update:

after changing the botkit version, node version, i can run the bot, but i got something like this 

![image](https://user-images.githubusercontent.com/11781111/73941984-d1735880-4920-11ea-94df-a8f7237499db.png)


Nothing happend after add the bot to the channel, and uploading APK.
